apiVersion: v1
kind: Service
metadata:
  name: java-app
  namespace: monitoring
  labels:
    app: java-app
spec:
  selector:
    app: java-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 9404
      targetPort: 9404
